// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVFcoZuOJY3U0v3ZFknkzFNFj1QCm5VHA',
    appId: '1:337246623306:web:4f1d9af60b0daf0254f8b3',
    messagingSenderId: '337246623306',
    projectId: 'amor-2246d',
    authDomain: 'amor-2246d.firebaseapp.com',
    storageBucket: 'amor-2246d.appspot.com',
    measurementId: 'G-7F2F59Z0NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhDDh6v6-ENbupjEiidhb2XNfS9JER0po',
    appId: '1:337246623306:android:c78e824775476e8c54f8b3',
    messagingSenderId: '337246623306',
    projectId: 'amor-2246d',
    storageBucket: 'amor-2246d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgBnKK8B2e9Sw76whhOxzvKMOWuo-CdM4',
    appId: '1:337246623306:ios:9ee2da55b6e684da54f8b3',
    messagingSenderId: '337246623306',
    projectId: 'amor-2246d',
    storageBucket: 'amor-2246d.appspot.com',
    iosClientId: '337246623306-v7ak5acm9vkc2bp2956soh7cfsp3phlb.apps.googleusercontent.com',
    iosBundleId: 'com.amor.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgBnKK8B2e9Sw76whhOxzvKMOWuo-CdM4',
    appId: '1:337246623306:ios:9ee2da55b6e684da54f8b3',
    messagingSenderId: '337246623306',
    projectId: 'amor-2246d',
    storageBucket: 'amor-2246d.appspot.com',
    iosClientId: '337246623306-v7ak5acm9vkc2bp2956soh7cfsp3phlb.apps.googleusercontent.com',
    iosBundleId: 'com.amor.app',
  );
}
